name: Build and Release ASI Mod

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure and Build with CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A Win32 ..
        cmake --build . --config Release

    - name: Package artifacts
      run: |
        mkdir artifacts
        copy "build\Release\*.asi" artifacts\ 2>nul || echo "No ASI files to copy"
        copy "build\Release\*.txt" artifacts\ 2>nul || echo "No TXT files to copy"
        echo "Artifacts ready:"
        dir artifacts

    - name: Upload to Releases
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
