name: Build and Release ASI Mod

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    # Set permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure and Build with CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A Win32 ..
        cmake --build . --config Release
    - name: Package artifacts
      run: |
        mkdir artifacts
        copy "build\Release\*.asi" artifacts\ 2>nul || echo "No ASI files to copy"
        copy "build\Release\*.ini" artifacts\ 2>nul || echo "No TXT files to copy"
        echo "Artifacts ready:"
        dir artifacts
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: artifacts/*
        body: |
          Automated build from GitHub Actions
          - Commit: ${{ github.sha }}
          - Triggered by: ${{ github.event_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
